[project]
name = "big-data-processing-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "findspark>=2.0.1",
    "jupyter>=1.1.1",
    "notebook>=7.4.5",
    "pyspark>=4.0.1",
]
